-- AlterEnum
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'Font';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'LUT';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'Plugin';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'Stock Footage';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'SFX';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'Motion Graphics';
