import { NavPreference } from '@/modules/core/ui/navigation'
import { PipelineIconName } from '@/lib/icons'

export type WorkflowPreset = {
  id: string
  name: string
  description: string
  icon: string
  navPreferences: NavPreference[]
  pipelineStages: { name: string; icon: PipelineIconName }[]
}

export const WORKFLOW_PRESETS: WorkflowPreset[] = [
  {
    id: 'developer',
    name: 'Developer / Agency',
    description: 'Optimized for software development, with focus on backlog, coding, and testing.',
    icon: '💻',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/feedback', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/assets', visible: false },
    ],
    pipelineStages: [
      { name: 'Backlog', icon: 'Library' },
      { name: 'To Do', icon: 'CheckCircle' },
      { name: 'In Progress', icon: 'Zap' },
      { name: 'Code Review', icon: 'GitBranch' },
      { name: 'Testing', icon: 'Bug' },
      { name: 'Deployed', icon: 'Rocket' }
    ],
  },
  {
    id: 'video-editor',
    name: 'Video Editor / Creator',
    description: 'Perfect for post-production workflows, including assembly, VFX, and client reviews.',
    icon: '🎬',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/prodp', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/assets', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/feedback', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/analytics', visible: true },
    ],
    pipelineStages: [
      { name: 'Ingestion', icon: 'Database' },
      { name: 'Assembly', icon: 'Layers' },
      { name: 'Rough Cut', icon: 'Scissors' },
      { name: 'VFX & Color', icon: 'Sparkles' },
      { name: 'Sound Design', icon: 'AudioWaveform' },
      { name: 'Client Review', icon: 'MonitorPlay' },
      { name: 'Final Render', icon: 'PackageCheck' }
    ],
  },
  {
    id: 'writer',
    name: 'Writer / Copywriter',
    description: 'Streamlined for drafting, editing, and publishing written content.',
    icon: '✍️',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/feedback', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/assets', visible: false },
    ],
    pipelineStages: [
      { name: 'Ideation', icon: 'Star' },
      { name: 'Outline', icon: 'Layout' },
      { name: 'First Draft', icon: 'PenLine' },
      { name: 'Self-Edit', icon: 'Edit3' },
      { name: 'Client Review', icon: 'MessageSquare' },
      { name: 'Final Revisions', icon: 'CheckCircle' },
      { name: 'Published', icon: 'BookOpen' }
    ],
  },
  {
    id: 'production-manager',
    name: 'Production Manager',
    description: 'Built for managing large shoots, casting, and overall production pipelines.',
    icon: '🎥',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/assets', visible: false },
      { href: '/dashboard/feedback', visible: false },
    ],
    pipelineStages: [
      { name: 'Pre-Production', icon: 'ClipboardList' },
      { name: 'Casting/Scouting', icon: 'Users' },
      { name: 'Production', icon: 'Film' },
      { name: 'Post-Production', icon: 'Scissors' },
      { name: 'Final Delivery', icon: 'PackageCheck' }
    ],
  },
  {
    id: 'business-owner',
    name: 'Business Owner / Sales',
    description: 'Focuses heavily on leads, financials, reports, and active contract negotiations.',
    icon: '🏢',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/assets', visible: false },
      { href: '/dashboard/feedback', visible: false },
    ],
    pipelineStages: [
      { name: 'Lead', icon: 'Users' },
      { name: 'Negotiation', icon: 'MessageSquare' },
      { name: 'Contract Sent', icon: 'FileText' },
      { name: 'Active', icon: 'Activity' },
      { name: 'Invoiced', icon: 'DollarSign' },
      { name: 'Paid', icon: 'CheckCircle' }
    ],
  },
  {
    id: 'graphic-designer',
    name: 'Graphic Designer / Illustrator',
    description: 'Tailored for visual design with focus on moodboarding, sketching, and final vector delivery.',
    icon: '🎨',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/assets', visible: true },
      { href: '/dashboard/feedback', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/analytics', visible: true },
    ],
    pipelineStages: [
      { name: 'Moodboard', icon: 'Layout' },
      { name: 'Sketch / Concept', icon: 'PenTool' },
      { name: 'Vectoring / Rendering', icon: 'Hexagon' },
      { name: 'Color & Polish', icon: 'Palette' },
      { name: 'Client Review', icon: 'MonitorPlay' },
      { name: 'Final Delivery', icon: 'PackageCheck' }
    ],
  },
  {
    id: 'audio-engineer',
    name: 'Audio Engineer / Producer',
    description: 'Optimized for music and podcast production, spanning recording to final master.',
    icon: '🎧',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/assets', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/feedback', visible: false },
    ],
    pipelineStages: [
      { name: 'Composition / Prep', icon: 'Music' },
      { name: 'Tracking / Recording', icon: 'Mic' },
      { name: 'Editing', icon: 'Scissors' },
      { name: 'Mixing', icon: 'SlidersHorizontal' },
      { name: 'Client Feedback', icon: 'MessageSquare' },
      { name: 'Mastering', icon: 'Speaker' }
    ],
  },
  {
    id: 'uiux-designer',
    name: 'UI/UX Designer',
    description: 'Perfect for product design teams managing research, wireframes, and developer handoffs.',
    icon: '✨',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/feedback', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/assets', visible: false },
    ],
    pipelineStages: [
      { name: 'Discovery / Research', icon: 'Search' },
      { name: 'Wireframes', icon: 'Layout' },
      { name: 'High-Fidelity', icon: 'Image' },
      { name: 'Prototyping', icon: 'Component' },
      { name: 'Usability Testing', icon: 'Users' },
      { name: 'Dev Handoff', icon: 'Code' }
    ],
  },
  {
    id: 'photographer',
    name: 'Photographer',
    description: 'Streamlined for photoshoots, culling, retouching, and sending final client galleries.',
    icon: '📸',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/assets', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/feedback', visible: false },
    ],
    pipelineStages: [
      { name: 'Pre-Shoot Planning', icon: 'ClipboardList' },
      { name: 'Shoot Day', icon: 'Film' },
      { name: 'Culling', icon: 'Layers' },
      { name: 'Color Correction', icon: 'Palette' },
      { name: 'Retouching', icon: 'Sparkles' },
      { name: 'Gallery Delivery', icon: 'PackageCheck' }
    ],
  },
  {
    id: 'teacher',
    name: 'Teacher / Educator',
    description: 'Designed for educators managing classes, assignments, and student feedback.',
    icon: '🧑‍🏫',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/clients', visible: true },
      { href: '/dashboard/financials', visible: true },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/assets', visible: false },
      { href: '/dashboard/feedback', visible: false },
    ],
    pipelineStages: [
      { name: 'Planning', icon: 'Book' },
      { name: 'Material Prep', icon: 'Library' },
      { name: 'In Progress', icon: 'Activity' },
      { name: 'Grading', icon: 'CheckCircle' },
      { name: 'Review', icon: 'MessageSquare' },
      { name: 'Completed', icon: 'GraduationCap' }
    ],
  },
  {
    id: 'student',
    name: 'Student / Learner',
    description: 'Optimized for tracking coursework, assignments, and personal study projects.',
    icon: '🎓',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/clients', visible: false },
      { href: '/dashboard/financials', visible: false },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/assets', visible: false },
      { href: '/dashboard/feedback', visible: false },
    ],
    pipelineStages: [
      { name: 'Not Started', icon: 'CircleDashed' },
      { name: 'Research / Study', icon: 'Search' },
      { name: 'In Progress', icon: 'Zap' },
      { name: 'Review', icon: 'MessageSquare' },
      { name: 'Submitted', icon: 'FileText' },
      { name: 'Graded', icon: 'GraduationCap' }
    ],
  },
  {
    id: 'researcher',
    name: 'Researcher / Analyst',
    description: 'Ideal for managing research projects, data collection, literature reviews, and publications.',
    icon: '🔬',
    navPreferences: [
      { href: '/dashboard', visible: true },
      { href: '/dashboard/messages', visible: true },
      { href: '/dashboard/projects', visible: true },
      { href: '/dashboard/pipeline', visible: true },
      { href: '/dashboard/assets', visible: true },
      { href: '/dashboard/analytics', visible: true },
      { href: '/dashboard/archive', visible: true },
      { href: '/dashboard/clients', visible: false },
      { href: '/dashboard/financials', visible: false },
      { href: '/dashboard/prodp', visible: false },
      { href: '/dashboard/feedback', visible: false },
    ],
    pipelineStages: [
      { name: 'Literature Review', icon: 'Library' },
      { name: 'Data Collection', icon: 'Database' },
      { name: 'Data Analysis', icon: 'Activity' },
      { name: 'Drafting', icon: 'PenLine' },
      { name: 'Peer Review', icon: 'MessageSquare' },
      { name: 'Published', icon: 'BookOpen' }
    ],
  },
]
